USE [ImagePRO]
GO

CREATE TABLE [dbo].[BARCODE](
	[ID] [int] NOT NULL,
	[TYPE] [varchar](30) NOT NULL,
 CONSTRAINT [PK_BARCODE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON
GO
/****** Object:  Table [dbo].[BATCH]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BATCH](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](30) NOT NULL,
	[JOB_ID] [int] NOT NULL,
	[WORKQUEUE_ID] [int] NOT NULL,
	[STATUS_ID] [int] NOT NULL,
	[PRIORITY] [int] NOT NULL,
	[FOLDER_PATH] [varchar](180) NOT NULL,
	[IMPORT_INPUT] [varchar](50) NULL,
 CONSTRAINT [PK_BATCH] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON
GO
/****** Object:  Table [dbo].[BATCH_COMMENT]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BATCH_COMMENT](
	[BATCH_ID] [int] NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
	[OPERATOR_NAME] [varchar](50) NOT NULL,
	[COMMENT] [text] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING ON
GO
/****** Object:  Table [dbo].[BATCH_HISTORY]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BATCH_HISTORY](
	[BATCH_ID] [int] NOT NULL,
	[NAME] [varchar](30) NOT NULL,
	[JOB_ID] [int] NOT NULL,
	[WORKQUEUE_ID] [int] NOT NULL,
	[STATUS_ID] [int] NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
	[MACHINE_NAME] [varchar](50) NULL,
	[OPERATOR_NAME] [varchar](50) NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING ON
GO
/****** Object:  Table [dbo].[FIELD]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FIELD](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PAGE_ID] [int] NOT NULL,
	[LABEL] [varchar](30) NOT NULL,
	[ZONE_X] [int] NOT NULL,
	[ZONE_Y] [int] NOT NULL,
	[ZONE_WIDTH] [int] NOT NULL,
	[ZONE_HEIGHT] [int] NOT NULL,
	[REGEX] [varchar](30) NOT NULL,
	[ACTIVE] [bit] NOT NULL,
 CONSTRAINT [PK_FIELD] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON
GO
/****** Object:  Table [dbo].[IMAGE]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IMAGE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SERIAL_NUMBER] [varchar](50) NOT NULL,
	[BATCH_ID] [int] NOT NULL,
	[PAGE_ID] [int] NULL,
	[FILE_NAME] [varchar](30) NOT NULL,
	[ENTRY] [varchar](1) NULL,
	[WIDTH] [int] NOT NULL,
	[HEIGHT] [int] NOT NULL,
	[SIZE] [int] NOT NULL,
	[DPI] [smallint] NOT NULL,
 CONSTRAINT [PK_IMAGE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON
GO
/****** Object:  Table [dbo].[IMAGE_DATA_BARCODE]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IMAGE_DATA_BARCODE](
	[IMAGE_ID] [int] NOT NULL,
	[WORKQUEUE_ID] [int] NOT NULL,
	[BARCODE_ID] [int] NOT NULL,
	[VALUE] [varchar](255) NULL,
 CONSTRAINT [PK_IMAGE_DATA_BARCODE] PRIMARY KEY CLUSTERED 
(
	[IMAGE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON
GO
/****** Object:  Table [dbo].[IMAGE_DATA_FIELD]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IMAGE_DATA_FIELD](
	[IMAGE_ID] [int] NOT NULL,
	[FIELD_ID] [int] NOT NULL,
	[VALUE] [varchar](80) NULL,
 CONSTRAINT [PK_IMAGE_DATA_FIELD] PRIMARY KEY CLUSTERED 
(
	[IMAGE_ID] ASC,
	[FIELD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON
GO
/****** Object:  Table [dbo].[INDEX_DATA]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[INDEX_DATA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[JOB_ID] [int] NULL,
	[BARCODE] [varchar](30) NULL,
	[VALUE1] [varchar](30) NULL,
	[VALUE2] [varchar](30) NOT NULL,
	[VALUE3] [varchar](30) NOT NULL,
	[VALUE4] [varchar](30) NOT NULL,
	[VALUE5] [varchar](30) NOT NULL,
	[OPERATOR_ID] [int] NULL,
	[CREATION_TIME] [datetime] NULL,
	[PRINTED] [bit] NULL,
 CONSTRAINT [PK_INDEX_DATA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON
GO
/****** Object:  Table [dbo].[JOB]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[JOB](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ABBREVIATION] [varchar](6) NOT NULL,
	[NAME] [varchar](40) NOT NULL,
	[ACTIVE] [bit] NOT NULL,
 CONSTRAINT [PK_JOB] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON
GO
/****** Object:  Table [dbo].[JOB_CONFIG_IBMLIMPORT]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[JOB_CONFIG_IBMLIMPORT](
	[JOB_ID] [int] NOT NULL,
	[WORKQUEUE_ID] [int] NOT NULL,
	[JOB_NAME] [varchar](40) NOT NULL,
	[STATUS_READY] [int] NOT NULL,
	[PRIORITY_DEFAULT] [int] NOT NULL CONSTRAINT [DF_JOB_CONFIG_IBMLIMPORT_PRIORITY_DEFAULT]  DEFAULT ((50)),
	[LOOP_COUNT] [int] NOT NULL CONSTRAINT [DF_JOB_CONFIG_IBMLIMPORT_LOOP_COUNT]  DEFAULT ((1)),
	[RELOCATE_IMAGE_FILES] [bit] NOT NULL CONSTRAINT [DF_JOB_CONFIG_IBMLIMPORT_RELOCATE_IMAGE_FILES]  DEFAULT ((0)),
	[WORKING_DIRECTORY] [varchar](80) NULL,
 CONSTRAINT [PK_JOB_CONFIG_IBMLIMPORT_1] PRIMARY KEY CLUSTERED 
(
	[JOB_ID] ASC,
	[WORKQUEUE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON
GO
/****** Object:  Table [dbo].[JOB_CONFIG_IMAGEANALYZE]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[JOB_CONFIG_IMAGEANALYZE](
	[JOB_ID] [int] NOT NULL,
	[WORKQUEUE_ID] [int] NOT NULL,
	[BLANK_PAGE_DETECTION] [bit] NOT NULL,
	[DESKEW] [bit] NOT NULL,
	[AUTO_ROTATE] [bit] NOT NULL,
	[BARCODE_CODE39] [bit] NOT NULL,
	[BARCODE_DATAMATRIX] [bit] NOT NULL,
	[LOOP_COUNT] [int] NOT NULL,
 CONSTRAINT [PK_JOB_CONFIG_IMAGEANALYZE_1] PRIMARY KEY CLUSTERED 
(
	[JOB_ID] ASC,
	[WORKQUEUE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[JOB_CONFIG_IMAGEQC]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[JOB_CONFIG_IMAGEQC](
	[JOB_ID] [int] NOT NULL,
	[WORKQUEUE_ID] [int] NOT NULL,
	[VALID_ENTRIES] [varchar](30) NOT NULL,
	[BLANK_CHAR] [varchar](1) NULL,
 CONSTRAINT [PK_JOB_CONFIG_IMAGEQC_1] PRIMARY KEY CLUSTERED 
(
	[JOB_ID] ASC,
	[WORKQUEUE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON
GO
/****** Object:  Table [dbo].[JOB_CONFIG_INDEX]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[JOB_CONFIG_INDEX](
	[JOB_ID] [int] NOT NULL,
	[LABEL1] [varchar](30) NOT NULL,
	[REGEX1] [varchar](30) NULL,
	[LABEL2] [varchar](30) NULL,
	[REGEX2] [varchar](30) NULL,
	[LABEL3] [varchar](30) NULL,
	[REGEX3] [varchar](30) NULL,
	[LABEL4] [varchar](30) NULL,
	[REGEX4] [varchar](30) NULL,
	[LABEL5] [varchar](30) NULL,
	[REGEX5] [varchar](30) NULL,
 CONSTRAINT [PK_JOB_CONFIG_INDEX] PRIMARY KEY CLUSTERED 
(
	[JOB_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON
GO
/****** Object:  Table [dbo].[OPERATOR]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OPERATOR](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](30) NOT NULL,
	[ADMIN] [bit] NOT NULL,
 CONSTRAINT [PK_OPERATOR] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON
GO
/****** Object:  Table [dbo].[OPERATOR_ACCESS]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OPERATOR_ACCESS](
	[OPERATOR_ID] [int] NOT NULL,
	[JOB_ID] [int] NOT NULL
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PAGE]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PAGE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](20) NOT NULL,
	[ACTIVE] [bit] NOT NULL,
 CONSTRAINT [PK_PAGE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON
GO
/****** Object:  Table [dbo].[STATUS]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[STATUS](
	[ID] [int] NOT NULL,
	[NAME] [varchar](50) NOT NULL,
 CONSTRAINT [PK_STATUS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON
GO
/****** Object:  Table [dbo].[WORK_QUEUE]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[WORK_QUEUE](
	[ID] [int] NOT NULL,
	[NAME] [varchar](50) NOT NULL,
 CONSTRAINT [PK_WORK_QUEUE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[JOB_CONFIG_IMAGEANALYZE] ADD  CONSTRAINT [DF_JOB_CONFIG_IMAGEANALYZE_BLANK_PAGE_DETECTION]  DEFAULT ((0)) FOR [BLANK_PAGE_DETECTION]
GO
ALTER TABLE [dbo].[JOB_CONFIG_IMAGEANALYZE] ADD  CONSTRAINT [DF_JOB_CONFIG_IMAGEANALYZE_DESKEW]  DEFAULT ((0)) FOR [DESKEW]
GO
ALTER TABLE [dbo].[JOB_CONFIG_IMAGEANALYZE] ADD  CONSTRAINT [DF_JOB_CONFIG_IMAGEANALYZE_AUTO_ROTATE]  DEFAULT ((0)) FOR [AUTO_ROTATE]
GO
ALTER TABLE [dbo].[JOB_CONFIG_IMAGEANALYZE] ADD  CONSTRAINT [DF_JOB_CONFIG_IMAGEANALYZE_BARCODE_CODE39]  DEFAULT ((0)) FOR [BARCODE_CODE39]
GO
ALTER TABLE [dbo].[JOB_CONFIG_IMAGEANALYZE] ADD  CONSTRAINT [DF_JOB_CONFIG_IMAGEANALYZE_BARCODE_DATAMATRIX]  DEFAULT ((0)) FOR [BARCODE_DATAMATRIX]
GO
ALTER TABLE [dbo].[JOB_CONFIG_IMAGEANALYZE] ADD  CONSTRAINT [DF_JOB_CONFIG_IMAGEANALYZE_LOOP_COUNT]  DEFAULT ((1)) FOR [LOOP_COUNT]
GO
ALTER TABLE [dbo].[OPERATOR] ADD  CONSTRAINT [DF_OPERATOR_ADMIN]  DEFAULT ((0)) FOR [ADMIN]
GO
ALTER TABLE [dbo].[BATCH]  WITH CHECK ADD  CONSTRAINT [FK_BATCH_JOB] FOREIGN KEY([JOB_ID])
REFERENCES [dbo].[JOB] ([ID])
GO
ALTER TABLE [dbo].[BATCH] CHECK CONSTRAINT [FK_BATCH_JOB]
GO
ALTER TABLE [dbo].[BATCH]  WITH CHECK ADD  CONSTRAINT [FK_BATCH_STATUS] FOREIGN KEY([STATUS_ID])
REFERENCES [dbo].[STATUS] ([ID])
GO
ALTER TABLE [dbo].[BATCH] CHECK CONSTRAINT [FK_BATCH_STATUS]
GO
ALTER TABLE [dbo].[BATCH]  WITH CHECK ADD  CONSTRAINT [FK_BATCH_WORK_QUEUE] FOREIGN KEY([WORKQUEUE_ID])
REFERENCES [dbo].[WORK_QUEUE] ([ID])
GO
ALTER TABLE [dbo].[BATCH] CHECK CONSTRAINT [FK_BATCH_WORK_QUEUE]
GO
ALTER TABLE [dbo].[BATCH_COMMENT]  WITH CHECK ADD  CONSTRAINT [FK_BATCH_COMMENT_BATCH] FOREIGN KEY([BATCH_ID])
REFERENCES [dbo].[BATCH] ([ID])
GO
ALTER TABLE [dbo].[BATCH_COMMENT] CHECK CONSTRAINT [FK_BATCH_COMMENT_BATCH]
GO
ALTER TABLE [dbo].[BATCH_HISTORY]  WITH CHECK ADD  CONSTRAINT [FK_BATCH_HISTORY_BATCH] FOREIGN KEY([BATCH_ID])
REFERENCES [dbo].[BATCH] ([ID])
GO
ALTER TABLE [dbo].[BATCH_HISTORY] CHECK CONSTRAINT [FK_BATCH_HISTORY_BATCH]
GO
ALTER TABLE [dbo].[BATCH_HISTORY]  WITH CHECK ADD  CONSTRAINT [FK_BATCH_HISTORY_JOB] FOREIGN KEY([JOB_ID])
REFERENCES [dbo].[JOB] ([ID])
GO
ALTER TABLE [dbo].[BATCH_HISTORY] CHECK CONSTRAINT [FK_BATCH_HISTORY_JOB]
GO
ALTER TABLE [dbo].[BATCH_HISTORY]  WITH CHECK ADD  CONSTRAINT [FK_BATCH_HISTORY_STATUS] FOREIGN KEY([STATUS_ID])
REFERENCES [dbo].[STATUS] ([ID])
GO
ALTER TABLE [dbo].[BATCH_HISTORY] CHECK CONSTRAINT [FK_BATCH_HISTORY_STATUS]
GO
ALTER TABLE [dbo].[BATCH_HISTORY]  WITH CHECK ADD  CONSTRAINT [FK_BATCH_HISTORY_WORK_QUEUE] FOREIGN KEY([WORKQUEUE_ID])
REFERENCES [dbo].[WORK_QUEUE] ([ID])
GO
ALTER TABLE [dbo].[BATCH_HISTORY] CHECK CONSTRAINT [FK_BATCH_HISTORY_WORK_QUEUE]
GO
ALTER TABLE [dbo].[FIELD]  WITH CHECK ADD  CONSTRAINT [FK_FIELD_PAGE] FOREIGN KEY([PAGE_ID])
REFERENCES [dbo].[PAGE] ([ID])
GO
ALTER TABLE [dbo].[FIELD] CHECK CONSTRAINT [FK_FIELD_PAGE]
GO
ALTER TABLE [dbo].[IMAGE]  WITH CHECK ADD  CONSTRAINT [FK_IMAGE_BATCH] FOREIGN KEY([BATCH_ID])
REFERENCES [dbo].[BATCH] ([ID])
GO
ALTER TABLE [dbo].[IMAGE] CHECK CONSTRAINT [FK_IMAGE_BATCH]
GO
ALTER TABLE [dbo].[IMAGE]  WITH CHECK ADD  CONSTRAINT [FK_IMAGE_PAGE] FOREIGN KEY([PAGE_ID])
REFERENCES [dbo].[PAGE] ([ID])
GO
ALTER TABLE [dbo].[IMAGE] CHECK CONSTRAINT [FK_IMAGE_PAGE]
GO
ALTER TABLE [dbo].[IMAGE_DATA_BARCODE]  WITH CHECK ADD  CONSTRAINT [FK_IMAGE_DATA_BARCODE_BARCODE] FOREIGN KEY([BARCODE_ID])
REFERENCES [dbo].[BARCODE] ([ID])
GO
ALTER TABLE [dbo].[IMAGE_DATA_BARCODE] CHECK CONSTRAINT [FK_IMAGE_DATA_BARCODE_BARCODE]
GO
ALTER TABLE [dbo].[IMAGE_DATA_BARCODE]  WITH CHECK ADD  CONSTRAINT [FK_IMAGE_DATA_BARCODE_IMAGE] FOREIGN KEY([IMAGE_ID])
REFERENCES [dbo].[IMAGE] ([ID])
GO
ALTER TABLE [dbo].[IMAGE_DATA_BARCODE] CHECK CONSTRAINT [FK_IMAGE_DATA_BARCODE_IMAGE]
GO
ALTER TABLE [dbo].[IMAGE_DATA_BARCODE]  WITH CHECK ADD  CONSTRAINT [FK_IMAGE_DATA_BARCODE_WORK_QUEUE] FOREIGN KEY([WORKQUEUE_ID])
REFERENCES [dbo].[WORK_QUEUE] ([ID])
GO
ALTER TABLE [dbo].[IMAGE_DATA_BARCODE] CHECK CONSTRAINT [FK_IMAGE_DATA_BARCODE_WORK_QUEUE]
GO
ALTER TABLE [dbo].[IMAGE_DATA_FIELD]  WITH CHECK ADD  CONSTRAINT [FK_IMAGE_DATA_FIELD_FIELD] FOREIGN KEY([FIELD_ID])
REFERENCES [dbo].[FIELD] ([ID])
GO
ALTER TABLE [dbo].[IMAGE_DATA_FIELD] CHECK CONSTRAINT [FK_IMAGE_DATA_FIELD_FIELD]
GO
ALTER TABLE [dbo].[IMAGE_DATA_FIELD]  WITH CHECK ADD  CONSTRAINT [FK_IMAGE_DATA_FIELD_IMAGE] FOREIGN KEY([IMAGE_ID])
REFERENCES [dbo].[IMAGE] ([ID])
GO
ALTER TABLE [dbo].[IMAGE_DATA_FIELD] CHECK CONSTRAINT [FK_IMAGE_DATA_FIELD_IMAGE]
GO
ALTER TABLE [dbo].[INDEX_DATA]  WITH CHECK ADD  CONSTRAINT [FK_INDEX_DATA_JOB] FOREIGN KEY([JOB_ID])
REFERENCES [dbo].[JOB] ([ID])
GO
ALTER TABLE [dbo].[INDEX_DATA] CHECK CONSTRAINT [FK_INDEX_DATA_JOB]
GO
ALTER TABLE [dbo].[INDEX_DATA]  WITH CHECK ADD  CONSTRAINT [FK_INDEX_DATA_OPERATOR] FOREIGN KEY([OPERATOR_ID])
REFERENCES [dbo].[OPERATOR] ([ID])
GO
ALTER TABLE [dbo].[INDEX_DATA] CHECK CONSTRAINT [FK_INDEX_DATA_OPERATOR]
GO
ALTER TABLE [dbo].[JOB_CONFIG_IBMLIMPORT]  WITH CHECK ADD  CONSTRAINT [FK_JOB_CONFIG_IBMLIMPORT_JOB] FOREIGN KEY([JOB_ID])
REFERENCES [dbo].[JOB] ([ID])
GO
ALTER TABLE [dbo].[JOB_CONFIG_IBMLIMPORT] CHECK CONSTRAINT [FK_JOB_CONFIG_IBMLIMPORT_JOB]
GO
ALTER TABLE [dbo].[JOB_CONFIG_IBMLIMPORT]  WITH CHECK ADD  CONSTRAINT [FK_JOB_CONFIG_IBMLIMPORT_WORK_QUEUE] FOREIGN KEY([WORKQUEUE_ID])
REFERENCES [dbo].[WORK_QUEUE] ([ID])
GO
ALTER TABLE [dbo].[JOB_CONFIG_IBMLIMPORT] CHECK CONSTRAINT [FK_JOB_CONFIG_IBMLIMPORT_WORK_QUEUE]
GO
ALTER TABLE [dbo].[JOB_CONFIG_IMAGEANALYZE]  WITH CHECK ADD  CONSTRAINT [FK_JOB_CONFIG_IMAGEANALYZE_JOB] FOREIGN KEY([JOB_ID])
REFERENCES [dbo].[JOB] ([ID])
GO
ALTER TABLE [dbo].[JOB_CONFIG_IMAGEANALYZE] CHECK CONSTRAINT [FK_JOB_CONFIG_IMAGEANALYZE_JOB]
GO
ALTER TABLE [dbo].[JOB_CONFIG_IMAGEANALYZE]  WITH CHECK ADD  CONSTRAINT [FK_JOB_CONFIG_IMAGEANALYZE_WORK_QUEUE] FOREIGN KEY([WORKQUEUE_ID])
REFERENCES [dbo].[WORK_QUEUE] ([ID])
GO
ALTER TABLE [dbo].[JOB_CONFIG_IMAGEANALYZE] CHECK CONSTRAINT [FK_JOB_CONFIG_IMAGEANALYZE_WORK_QUEUE]
GO
ALTER TABLE [dbo].[JOB_CONFIG_IMAGEQC]  WITH CHECK ADD  CONSTRAINT [FK_JOB_CONFIG_IMAGEQC_JOB] FOREIGN KEY([JOB_ID])
REFERENCES [dbo].[JOB] ([ID])
GO
ALTER TABLE [dbo].[JOB_CONFIG_IMAGEQC] CHECK CONSTRAINT [FK_JOB_CONFIG_IMAGEQC_JOB]
GO
ALTER TABLE [dbo].[JOB_CONFIG_IMAGEQC]  WITH CHECK ADD  CONSTRAINT [FK_JOB_CONFIG_IMAGEQC_WORK_QUEUE] FOREIGN KEY([WORKQUEUE_ID])
REFERENCES [dbo].[WORK_QUEUE] ([ID])
GO
ALTER TABLE [dbo].[JOB_CONFIG_IMAGEQC] CHECK CONSTRAINT [FK_JOB_CONFIG_IMAGEQC_WORK_QUEUE]
GO
ALTER TABLE [dbo].[JOB_CONFIG_INDEX]  WITH CHECK ADD  CONSTRAINT [FK_JOB_CONFIG_INDEX_JOB] FOREIGN KEY([JOB_ID])
REFERENCES [dbo].[JOB] ([ID])
GO
ALTER TABLE [dbo].[JOB_CONFIG_INDEX] CHECK CONSTRAINT [FK_JOB_CONFIG_INDEX_JOB]
GO
ALTER TABLE [dbo].[OPERATOR_ACCESS]  WITH CHECK ADD  CONSTRAINT [FK_OPERATOR_ACCESS_JOB] FOREIGN KEY([JOB_ID])
REFERENCES [dbo].[JOB] ([ID])
GO
ALTER TABLE [dbo].[OPERATOR_ACCESS] CHECK CONSTRAINT [FK_OPERATOR_ACCESS_JOB]
GO
ALTER TABLE [dbo].[OPERATOR_ACCESS]  WITH CHECK ADD  CONSTRAINT [FK_OPERATOR_ACCESS_OPERATOR] FOREIGN KEY([OPERATOR_ID])
REFERENCES [dbo].[OPERATOR] ([ID])
GO
ALTER TABLE [dbo].[OPERATOR_ACCESS] CHECK CONSTRAINT [FK_OPERATOR_ACCESS_OPERATOR]
GO
/****** Object:  StoredProcedure [dbo].[GET_IMAGE_BARCODE]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GET_IMAGE_BARCODE]
	@IMAGE_ID int
AS
BEGIN
	SELECT WORKQUEUE_ID, BARCODE_ID, VALUE
	  FROM IMAGE_DATA_BARCODE
	 WHERE IMAGE_ID = @IMAGE_ID
END
GO
/****** Object:  StoredProcedure [dbo].[GET_IMAGE_ENTRY]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GET_IMAGE_ENTRY]
	@BATCH_ID int
AS
BEGIN
	SELECT IMAGE.ID,
	       BATCH.FOLDER_PATH + IMAGE.FILE_NAME AS IMAGEPATH,
		   ISNULL(CONVERT(varchar(1), IMAGE.ENTRY), '') AS IMAGE_ENTRY
	  FROM BATCH
	  JOIN IMAGE
		ON BATCH.ID = IMAGE.BATCH_ID
	 WHERE BATCH.ID = @BATCH_ID
	 ORDER BY IMAGE.SERIAL_NUMBER
END
GO
/****** Object:  StoredProcedure [dbo].[GET_IMAGE_ENTRY_NOBLANKS]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GET_IMAGE_ENTRY_NOBLANKS]
	@BATCH_ID int
AS
BEGIN
	SELECT IMAGE.ID,
	       BATCH.FOLDER_PATH + IMAGE.FILE_NAME AS IMAGEPATH,
		   ISNULL(CONVERT(varchar(1), IMAGE.ENTRY), '') AS IMAGE_ENTRY
	  FROM BATCH
	  JOIN IMAGE
		ON BATCH.ID = IMAGE.BATCH_ID
	  LEFT OUTER JOIN JOB_CONFIG_IMAGEQC
	    ON JOB_CONFIG_IMAGEQC.JOB_ID = (SELECT BATCH.JOB_ID WHERE BATCH.ID = IMAGE.BATCH_ID)
	 WHERE BATCH.ID = @BATCH_ID
	   AND (IMAGE.ENTRY IS NULL OR NOT IMAGE.ENTRY = JOB_CONFIG_IMAGEQC.BLANK_CHAR)
	 ORDER BY IMAGE.SERIAL_NUMBER
END
GO
/****** Object:  StoredProcedure [dbo].[GET_NEXTBATCH]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GET_NEXTBATCH]
    @JOB_ID int,
	@WORKQUEUE_ID int,
	@STATUS_READY int,
	@STATUS_INPROGRESS int,
	@NEXTBATCH int OUTPUT
AS
BEGIN

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE

BEGIN TRANSACTION

	SET @NEXTBATCH = (SELECT TOP(1) BATCH.ID  
	                           FROM BATCH 
						      WHERE BATCH.JOB_ID = @JOB_ID
						        AND BATCH.WORKQUEUE_ID = @WORKQUEUE_ID
								AND BATCH.STATUS_ID = @STATUS_READY
						   ORDER BY BATCH.PRIORITY, BATCH.ID)

	IF @NEXTBATCH IS NOT NULL
		BEGIN
			UPDATE BATCH WITH (ROWLOCK) 
			   SET BATCH.STATUS_ID = @STATUS_INPROGRESS 
			 WHERE BATCH.ID = @NEXTBATCH
		END
	ELSE
		BEGIN
			SET @NEXTBATCH = NULL
		END

COMMIT TRANSACTION

SELECT @NEXTBATCH AS NEXTBATCH

END
GO
/****** Object:  StoredProcedure [dbo].[INSERT_BATCH]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[INSERT_BATCH]
	@NAME varchar(30),
	@JOB_ID int,
	@WORKQUEUE_ID int,
	@STATUS_ID int,
	@PRIORITY int,
	@FOLDER_PATH varchar(180),
	@IMPORT_INPUT varchar(50),
	@BATCH_ID int OUTPUT
AS
BEGIN
	INSERT INTO BATCH (NAME, JOB_ID, WORKQUEUE_ID, STATUS_ID, PRIORITY, FOLDER_PATH, IMPORT_INPUT) 
	     VALUES (@NAME, @JOB_ID, @WORKQUEUE_ID, @STATUS_ID, @PRIORITY, @FOLDER_PATH, @IMPORT_INPUT)

	SET @BATCH_ID = SCOPE_IDENTITY();
END
GO
/****** Object:  StoredProcedure [dbo].[INSERT_IMAGE]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[INSERT_IMAGE]
	@SERIAL_NUMBER varchar(50),
	@BATCH_ID int,
	@PAGE_ID int,
	@FILE_NAME varchar(30),
	@ENTRY varchar(1),
	@WIDTH int,
	@HEIGHT int,
	@SIZE int,
	@DPI smallint,
	@IMAGE_ID int OUTPUT
AS
	INSERT INTO IMAGE (SERIAL_NUMBER, BATCH_ID, PAGE_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
	           VALUES (@SERIAL_NUMBER, @BATCH_ID, @PAGE_ID, @FILE_NAME, @ENTRY, @WIDTH, @HEIGHT, @SIZE, @DPI)

	SET @IMAGE_ID = SCOPE_IDENTITY();
GO
/****** Object:  StoredProcedure [dbo].[INSERT_IMAGE_BARCODE]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[INSERT_IMAGE_BARCODE]
	@IMAGE_ID int,
	@WORKQUEUE_ID int,
	@BARCODE_ID int,
	@VALUE varchar(255)
AS
	INSERT INTO IMAGE_DATA_BARCODE (IMAGE_ID, WORKQUEUE_ID, BARCODE_ID, VALUE) 
         VALUES (@IMAGE_ID, @WORKQUEUE_ID, @BARCODE_ID, @VALUE)
GO
/****** Object:  StoredProcedure [dbo].[UPDATE_BATCH_IMPORTINPUT]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[UPDATE_BATCH_IMPORTINPUT]
	@BATCH_ID int,
	@IMPORT_INPUT varchar(50)
AS
	UPDATE BATCH SET IMPORT_INPUT = @IMPORT_INPUT WHERE ID = @BATCH_ID
RETURN 0
GO
/****** Object:  StoredProcedure [dbo].[UPDATE_BATCH_STATUS]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[UPDATE_BATCH_STATUS]
	@BATCH_ID int,
	@STATUS_ID int
AS
	UPDATE BATCH SET STATUS_ID = @STATUS_ID WHERE ID = @BATCH_ID
RETURN 0
GO
/****** Object:  StoredProcedure [dbo].[UPDATE_BATCH_WORKQUEUE]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[UPDATE_BATCH_WORKQUEUE]
	@BATCH_ID int,
	@WORKQUEUE_ID int,
	@STATUS_ID int
AS
	UPDATE BATCH SET WORKQUEUE_ID = @WORKQUEUE_ID, 
	                 STATUS_ID = @STATUS_ID
			   WHERE ID = @BATCH_ID
RETURN 0
GO
/****** Object:  StoredProcedure [dbo].[UPDATE_IMAGE_ENTRY]    Script Date: 6/2/2017 4:53:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[UPDATE_IMAGE_ENTRY]
	@IMAGE_ID int,
	@IMAGE_ENTRY varchar(1)
AS
	UPDATE IMAGE SET IMAGE.ENTRY = @IMAGE_ENTRY WHERE IMAGE.ID = @IMAGE_ID
RETURN 0
GO

/*  * * * STATUS * * *  */

IF NOT EXISTS(SELECT * FROM dbo.[STATUS] WHERE ID = 0)
	INSERT INTO dbo.[STATUS] (ID, NAME)
	     VALUES (0, 'READY')

IF NOT EXISTS(SELECT * FROM dbo.[STATUS] WHERE ID = 1)
	INSERT INTO dbo.[STATUS] (ID, NAME)
	     VALUES (1, 'IN PROGRESS')

IF NOT EXISTS(SELECT * FROM dbo.[STATUS] WHERE ID = 2)
	INSERT INTO dbo.[STATUS] (ID, NAME)
	     VALUES (2, 'HOLD')

IF NOT EXISTS(SELECT * FROM dbo.[STATUS] WHERE ID = 3)
	INSERT INTO dbo.[STATUS] (ID, NAME)
	     VALUES (3, 'COMPLETE')

IF NOT EXISTS(SELECT * FROM dbo.[STATUS] WHERE ID = 4)
	INSERT INTO dbo.[STATUS] (ID, NAME)
	     VALUES (4, 'DELETED')

IF NOT EXISTS(SELECT * FROM dbo.[STATUS] WHERE ID = 5)
	INSERT INTO dbo.[STATUS] (ID, NAME)
	     VALUES (5, 'ERROR')


/*  * * * WORK QUEUE * * *  */
IF NOT EXISTS(SELECT * FROM dbo.[WORK_QUEUE] WHERE ID = 10)
	INSERT INTO dbo.[WORK_QUEUE] (ID, NAME) 
	     VALUES (10, 'IBML IMPORT')

IF NOT EXISTS(SELECT * FROM dbo.[WORK_QUEUE] WHERE ID = 11)
	INSERT INTO dbo.[WORK_QUEUE] (ID, NAME) 
	     VALUES (11, 'IBML 6450 IMPORT')

IF NOT EXISTS(SELECT * FROM dbo.[WORK_QUEUE] WHERE ID = 12)
	INSERT INTO dbo.[WORK_QUEUE] (ID, NAME) 
	     VALUES (12, 'TMS IMPORT')

IF NOT EXISTS(SELECT * FROM dbo.[WORK_QUEUE] WHERE ID = 13)
	INSERT INTO dbo.[WORK_QUEUE] (ID, NAME) 
	     VALUES (13, 'CUSTOM IMPORT')

IF NOT EXISTS(SELECT * FROM dbo.[WORK_QUEUE] WHERE ID = 20)
	INSERT INTO dbo.[WORK_QUEUE] (ID, NAME) 
	     VALUES (20, 'IMAGE ANALYZE')

IF NOT EXISTS(SELECT * FROM dbo.[WORK_QUEUE] WHERE ID = 30)
	INSERT INTO dbo.[WORK_QUEUE] (ID, NAME) 
	     VALUES (30, 'IMAGE QC')

IF NOT EXISTS(SELECT * FROM dbo.[WORK_QUEUE] WHERE ID = 40)
	INSERT INTO dbo.[WORK_QUEUE] (ID, NAME) 
	     VALUES (40, 'COMPLETION')

IF NOT EXISTS(SELECT * FROM dbo.[WORK_QUEUE] WHERE ID = 50)
	INSERT INTO dbo.[WORK_QUEUE] (ID, NAME) 
	     VALUES (50, 'PULL')

IF NOT EXISTS(SELECT * FROM dbo.[WORK_QUEUE] WHERE ID = 55)
	INSERT INTO dbo.[WORK_QUEUE] (ID, NAME) 
	     VALUES (55, 'RESCAN')

IF NOT EXISTS(SELECT * FROM dbo.[WORK_QUEUE] WHERE ID = 60)
	INSERT INTO dbo.[WORK_QUEUE] (ID, NAME) 
	     VALUES (60, 'PDF CREATION')

IF NOT EXISTS(SELECT * FROM dbo.[WORK_QUEUE] WHERE ID = 65)
	INSERT INTO dbo.[WORK_QUEUE] (ID, NAME) 
	     VALUES (65, 'FILE EXPORT')

IF NOT EXISTS(SELECT * FROM dbo.[WORK_QUEUE] WHERE ID = 66)
	INSERT INTO dbo.[WORK_QUEUE] (ID, NAME) 
	     VALUES (66, 'ONBASE EXPORT')

IF NOT EXISTS(SELECT * FROM dbo.[WORK_QUEUE] WHERE ID = 67)
	INSERT INTO dbo.[WORK_QUEUE] (ID, NAME) 
	     VALUES (67, 'INFOIMAGE EXPORT')

IF NOT EXISTS(SELECT * FROM dbo.[WORK_QUEUE] WHERE ID = 80)
	INSERT INTO dbo.[WORK_QUEUE] (ID, NAME) 
	     VALUES (80, 'TRANSFER')

IF NOT EXISTS(SELECT * FROM dbo.[WORK_QUEUE] WHERE ID = 90)
	INSERT INTO dbo.[WORK_QUEUE] (ID, NAME) 
	     VALUES (90, 'CLEANUP')


/*  * * * BARCODE TYPES * * *  */

IF NOT EXISTS(SELECT * FROM dbo.[BARCODE] WHERE ID = 1)
	INSERT INTO dbo.[BARCODE] (ID, TYPE) 
	     VALUES (1, 'CODE39')

IF NOT EXISTS(SELECT * FROM dbo.[BARCODE] WHERE ID = 2)
	INSERT INTO dbo.[BARCODE] (ID, TYPE) 
	     VALUES (2, 'DATAMATRIX')

/* * * * * * * * * * * * * * * * * *
   *                               *
   *   CLEAR PREVIOUS TEST DATA    *
   *                               *
   * * * * * * * * * * * * * * * * * */

DELETE FROM IMAGE_DATA_FIELD
DELETE FROM IMAGE_DATA_BARCODE
DELETE FROM IMAGE
DELETE FROM FIELD
DELETE FROM PAGE
DELETE FROM BATCH_HISTORY
DELETE FROM BATCH_COMMENT
DELETE FROM BATCH
DELETE FROM JOB_CONFIG_IBMLIMPORT
DELETE FROM JOB_CONFIG_IMAGEQC
DELETE FROM JOB

/* * * * * * * * * * * * * * * * * *
   *                               *
   *       INSERT TEST DATA        *
   *                               *
   * * * * * * * * * * * * * * * * * */

SET IDENTITY_INSERT JOB ON

INSERT INTO JOB (ID, ABBREVIATION, NAME, ACTIVE)
         VALUES (1, 'TST', 'TEST JOB', 1)

INSERT INTO JOB (ID, ABBREVIATION, NAME, ACTIVE)
         VALUES (2, 'PBPP', 'PAROLE', 1)

SET IDENTITY_INSERT JOB OFF


INSERT INTO JOB_CONFIG_IBMLIMPORT (JOB_ID, WORKQUEUE_ID, JOB_NAME, STATUS_READY, PRIORITY_DEFAULT, LOOP_COUNT, RELOCATE_IMAGE_FILES, WORKING_DIRECTORY)
                           VALUES (1, 10, 'TEST_IBML', 5, 50, 10, 0, NULL)
INSERT INTO JOB_CONFIG_IBMLIMPORT (JOB_ID, WORKQUEUE_ID, JOB_NAME, STATUS_READY, PRIORITY_DEFAULT, LOOP_COUNT, RELOCATE_IMAGE_FILES, WORKING_DIRECTORY)
                           VALUES (2, 11, 'PBPP', 2, 50, 10, 1, 'C:\IPTestBatches\PAROLE')

INSERT INTO JOB_CONFIG_IMAGEQC (JOB_ID, WORKQUEUE_ID, VALID_ENTRIES, BLANK_CHAR)
                        VALUES (1, 30, 'B,D,S', 'B')
INSERT INTO JOB_CONFIG_IMAGEQC (JOB_ID, WORKQUEUE_ID, VALID_ENTRIES, BLANK_CHAR)
                        VALUES (2, 30, 'B,D,R,S', 'B')

SET IDENTITY_INSERT BATCH ON

INSERT INTO BATCH (ID, NAME, JOB_ID, WORKQUEUE_ID, STATUS_ID, PRIORITY, FOLDER_PATH, IMPORT_INPUT)
           VALUES (1, 'TST2017030100001', 1, 30, 0, 50, 'C:\IPTestBatches\TEST\TST2017030100001\', '')
INSERT INTO BATCH (ID, NAME, JOB_ID, WORKQUEUE_ID, STATUS_ID, PRIORITY, FOLDER_PATH, IMPORT_INPUT)
           VALUES (2, 'TST2017030100002', 1, 30, 0, 50, 'C:\IPTestBatches\TEST\TST2017030100002\', '')
INSERT INTO BATCH (ID, NAME, JOB_ID, WORKQUEUE_ID, STATUS_ID, PRIORITY, FOLDER_PATH, IMPORT_INPUT)
           VALUES (3, 'PBPP2017030100000', 2, 30, 0, 50, 'C:\IPTestBatches\PAROLE\PBPP2017030100000\', '')
INSERT INTO BATCH (ID, NAME, JOB_ID, WORKQUEUE_ID, STATUS_ID, PRIORITY, FOLDER_PATH, IMPORT_INPUT)
           VALUES (4, 'PBPP2017030100001', 2, 30, 0, 50, 'C:\IPTestBatches\PAROLE\PBPP2017030100001\', '')
INSERT INTO BATCH (ID, NAME, JOB_ID, WORKQUEUE_ID, STATUS_ID, PRIORITY, FOLDER_PATH, IMPORT_INPUT)
           VALUES (5, 'PBPP2017030100002', 2, 30, 0, 50, 'C:\IPTestBatches\PAROLE\PBPP2017030100002\', '')

SET IDENTITY_INSERT BATCH OFF

SET IDENTITY_INSERT IMAGE ON

INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (1, 'TST20170301000010001F', 1, 'F0000001.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (2, 'TST20170301000010001R', 1, 'R0000001.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (3, 'TST20170301000010002F', 1, 'F0000002.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (4, 'TST20170301000010002R', 1, 'R0000002.tif', NULL, 1400, 3300, 25000, 300)

INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (5, 'TST20170301000020001F', 2, 'F0000004.tif', 'S', 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (6, 'TST20170301000020001R', 2, 'R0000004.tif', 'B', 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (7, 'TST20170301000020002F', 2, 'F0000005.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (8, 'TST20170301000020002R', 2, 'R0000005.tif', NULL, 1400, 3300, 25000, 300)

INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (9, 'PBPP20170301000000001F', 3, 'F0000007.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (10, 'PBPP20170301000000001R', 3, 'R0000007.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (11, 'PBPP20170301000000002F', 3, 'F0000008.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (12, 'PBPP20170301000000002R', 3, 'R0000008.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (13, 'PBPP20170301000000003F', 3, 'F0000009.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (14, 'PBPP20170301000000003R', 3, 'R0000009.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (15, 'PBPP20170301000000004F', 3, 'F0000010.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (16, 'PBPP20170301000000004R', 3, 'R0000010.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (17, 'PBPP20170301000000005F', 3, 'F0000011.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (18, 'PBPP20170301000000005R', 3, 'R0000011.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (19, 'PBPP20170301000000006F', 3, 'F0000012.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (20, 'PBPP20170301000000006R', 3, 'R0000012.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (21, 'PBPP20170301000000007F', 3, 'F0000013.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (22, 'PBPP20170301000000007R', 3, 'R0000013.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (23, 'PBPP20170301000000008F', 3, 'F0000014.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (24, 'PBPP20170301000000008R', 3, 'R0000014.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (25, 'PBPP20170301000000009F', 3, 'F0000015.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (26, 'PBPP20170301000000009R', 3, 'R0000015.tif', NULL, 1400, 3300, 25000, 300)

INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (27, 'PBPP20170301000010001F', 4, 'F0000027.tif', 'S', 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (28, 'PBPP20170301000010001R', 4, 'R0000027.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (29, 'PBPP20170301000010002F', 4, 'F0000028.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (30, 'PBPP20170301000010002R', 4, 'R0000028.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (31, 'PBPP20170301000010003F', 4, 'F0000029.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (32, 'PBPP20170301000010003R', 4, 'R0000029.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (33, 'PBPP20170301000010004F', 4, 'F0000030.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (34, 'PBPP20170301000010004R', 4, 'R0000030.tif', 'B', 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (35, 'PBPP20170301000010005F', 4, 'F0000031.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (36, 'PBPP20170301000010005R', 4, 'R0000031.tif', 'B', 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (37, 'PBPP20170301000010006F', 4, 'F0000032.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (38, 'PBPP20170301000010006R', 4, 'R0000032.tif', 'B', 1400, 3300, 25000, 300)

INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (39, 'PBPP20170301000020001F', 5, 'F0000040.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (40, 'PBPP20170301000020001R', 5, 'R0000040.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (41, 'PBPP20170301000020002F', 5, 'F0000041.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (42, 'PBPP20170301000020002R', 5, 'R0000041.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (43, 'PBPP20170301000020003F', 5, 'F0000042.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (44, 'PBPP20170301000020003R', 5, 'R0000042.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (45, 'PBPP20170301000020004F', 5, 'F0000043.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (46, 'PBPP20170301000020004R', 5, 'R0000043.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (47, 'PBPP20170301000020005F', 5, 'F0000044.tif', NULL, 1400, 3300, 25000, 300)
INSERT INTO IMAGE (ID, SERIAL_NUMBER, BATCH_ID, FILE_NAME, ENTRY, WIDTH, HEIGHT, SIZE, DPI)
           VALUES (48, 'PBPP20170301000020005R', 5, 'R0000044.tif', NULL, 1400, 3300, 25000, 300)

SET IDENTITY_INSERT IMAGE OFF
GO
